config/routes.rb
Rails.application.routes.draw do

  get '/profile' => 'home#profile', as: 'home_profile'
  get '/category/:id' => 'home#category', as: 'home_category'
  get '/work/:id' => 'home#work', as: 'home_work'
  get '/contact' => 'home#contact', as: 'home_contact'

  root 'home#index'

  namespace :admin do
    root 'infos#edit'
    resources :categories do
      resources :works
    end
    resources :infos
    resources :profiles
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < AdminController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @types = [
      "",
      "E&E",
      "PROJ",
      "EXB"
    ]
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to [:admin, @profile], notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to [:admin, @profile], notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to admin_profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:list, :worked_at, :title)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/profiles/_form.html.erb
<%= form_for([:admin, profile]) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list %>
    <%= f.select :list, options_for_select([['EDUCATION & EXPERIENCE', 1], ['PROJECTS', 2], ['EXHIBITIONS', 3]], 1) %>
  </div>

  <div class="field">
    <%= f.label :worked_at %>
    <%= f.text_area :worked_at %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', [:admin, @profile] %> |
<%= link_to 'Back', admin_profiles_path %>

app/views/admin/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profile 리스트</h1>

<table>
  <thead>
    <tr>
      <th>종류</th>
      <th>Worked at</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= @types[profile.list] %></td>
        <td><%= profile.worked_at %></td>
        <td><%= profile.title %></td>
        <td><%= link_to '수정하기', edit_admin_profile_path(profile) %></td>
        <td><%= link_to '삭제하기', [:admin, profile], method: :delete, data: { confirm: '정말 삭제하겠습니까?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '새 Profile 생성', new_admin_profile_path %>

app/views/admin/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', admin_profiles_path %>

app/views/admin/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List:</strong>
  <%= @profile.list %>
</p>

<p>
  <strong>Worked at:</strong>
  <%= @profile.worked_at %>
</p>

<p>
  <strong>Title:</strong>
  <%= @profile.title %>
</p>

<%= link_to 'Edit', edit_admin_profile_path(@profile) %> |
<%= link_to 'Back', admin_profiles_path %>