config/routes.rb
Rails.application.routes.draw do

  get '/profile' => 'home#profile', as: 'home_profile'
  get '/category/:id' => 'home#category', as: 'home_category'
  get '/work/:id' => 'home#work', as: 'home_work'
  get '/contact' => 'home#contact', as: 'home_contact'

  root 'home#index'

  namespace :admin do
    root 'infos#edit'
    resources :categories do
      resources :works
    end
    resources :infos
    resources :profiles
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @content = Info.last.nil? ? 'not updated' : Info.last.home
  end

  def profile
    @data1 = Profile.where(list: 1).all
    @data2 = Profile.where(list: 2).all
    @data3 = Profile.where(list: 3).all
  end

  def category
    @categories = Category.all
    @category = Category.where(id: params[:id]).first
    @works = @category.works.all
    @is_work = "container-fluid-category"
  end

  def work
    @categories = Category.all
    @work = Work.where(id: params[:id]).first
    @pictures = @work.pictures
    @category = @work.category
    @is_work = "container-fluid-category"
  end

  def contact
    info = Info.last
    @website = info.nil? ? "not upadted" : info.website
    @email = info.nil? ? "not upadted" : info.email
    @address = info.nil? ? "not upadted" : info.address
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_category_navigation.html.erb
<ul class='navigation-ul'>
  <% Category.all.each_with_index do |category, index| %>
    <li id="<%=type%>c<%=category.id%>">
      <%= link_to category.title, home_category_path(category) %>
    </li>
  <% end %>
</ul>

app/views/home/_main_header.html.erb
<div id='main-header'>
  <div id='navigation'>
    <div id='menu-open' class='menu-open' onclick='openMenu()'>
      MENU
    </div>
    <ul class='navigation-ul' id='main-menu'>
      <li id='m1'><%= link_to '01. <br>HOME'.html_safe, root_path %></li>
      <li id='m2'><%= link_to '02. <br>PROFILE'.html_safe, home_profile_path %></li>
      <li id='md3' class='od'><%= link_to '03. <br>WORKS'.html_safe, Category.first.nil? ? '#' : home_category_path(Category.first) %>
      </li>
      <li id='mm3' class='om'><%= link_to '03. <br>WORKS'.html_safe, 'javascript:openWorks();' %>
        <div id='mobile-category-navigation'>
          <%= render 'home/category_navigation', type: "m" %>
        </div>
      </li>
      <li id='m4'><%= link_to '04. <br>CONTACT'.html_safe, home_contact_path %></li>
    </ul>
  </div>
</div>

<script>
  function openMenu() {
    $("#menu-open").attr("onclick", "closeMenu()");
    $("#content").hide();
    $("#main-menu").show();
  }

  function closeMenu() {
    $("#menu-open").attr("onclick", "openMenu()");
    $("#content").show();
    $("#main-menu").hide();
  }

  function openWorks() {
    $("#mobile-category-navigation").show();
  }
</script>

app/views/home/category.html.erb
<div id='category-navigation'>
  <%= render 'home/category_navigation', type: "d" %>
</div>
<div class='category'>
  <div class='works'>
    <% @works.each do |work| %>
      <%= link_to home_work_path(work) do %>
      <div class='work-item'>
        <div class='image' style='background-image: url("<%= image_url work.pictures.first.avatar_url %>")'>
          <%= image_tag work.pictures.first.avatar.thumb.url %>
        </div>
        <h3 class='title'>
          <%= work.title %>
        </h3>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#mm3').addClass("active");
    $('#md3').addClass("active");
    $("#dc<%=@category.id%>").addClass("active");
    $("#mc<%=@category.id%>").addClass("active");
  });
</script>

app/views/home/contact.html.erb
<div class='contact'>
  <div class='column'>
    <h2>WEBSITE</h2>
    <p><%= @website.html_safe %>
  </div>
  <div class='column'>
    <h2>E-MAIL</h2>
    <p><%= @email.html_safe %>
  </div>
  <div class='column'>
    <h2>ADDRESS</h2>
    <p><%= @address.html_safe %>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('#m4').addClass("active");
  });
</script>

app/views/home/index.html.erb
<p class='home'><%= @content %></p>

<script>
  $(document).ready(function() {
    $('#m1').addClass("active");
  });
</script>

app/views/home/profile.html.erb
<div class='profile'>
  <div class='column'>
    <h2>EDUCATION <br>& EXPERIENCE</h2>
    <% @data1.each do |data| %>
      <div class='row'>
        <span><%= data.worked_at %></span>
        <p><%= data.title %></p>
      </div>
    <% end %>
  </div>
  <div class='column'>
    <h2>PROJECTS</h2>
    <% @data2.each do |data| %>
      <div class='row'>
        <span><%= data.worked_at %></span>
        <p><%= data.title %></p>
      </div>
    <% end %>
  </div>
  <div class='column'>
    <h2>EXHIBITIONS</h2>
    <% @data3.each do |data| %>
      <div class='row'>
        <span><%= data.worked_at %></span>
        <p><%= data.title %></p>
      </div>
    <% end %>
  </div>
</div>
<script>
  $(document).ready(function() {
    $('#m2').addClass("active");
  });
</script>

app/views/home/work.html.erb
<div id='category-navigation'>
  <%= render 'home/category_navigation', type: "d" %>
</div>
<div class='work'>
  <div class='images'>
    <% @pictures.each do |picture| %>
      <%= image_tag picture.avatar.thumb_large.url %>
    <% end %>
  </div>
  <div class='row'>
    <h1><%= @work.title.html_safe %></h1>
    <span><%= @work.worked_at.html_safe %></span>
  </div>
  <p><%= @work.content %></p>
</div>

<script>
  $(document).ready(function() {
    $('#mm3').addClass("active");
    $('#md3').addClass("active");
    $("#dc<%=@category.id%>").addClass("active");
    $("#mc<%=@category.id%>").addClass("active");
  });
</script>