config/routes.rb
Rails.application.routes.draw do

  get '/profile' => 'home#profile', as: 'home_profile'
  get '/category/:id' => 'home#category', as: 'home_category'
  get '/work/:id' => 'home#work', as: 'home_work'
  get '/contact' => 'home#contact', as: 'home_contact'

  root 'home#index'

  namespace :admin do
    root 'infos#edit'
    resources :categories do
      resources :works
    end
    resources :infos
    resources :profiles
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :category
  has_many :pictures, :dependent => :destroy
  accepts_nested_attributes_for :pictures

end

app/controllers/admin/works_controller.rb
class Admin::WorksController < AdminController
  before_action :set_category
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = @category.works.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @pictures = @work.pictures.all
  end

  # GET /works/new
  def new
    @work = @category.works.new
    @pictures = @work.pictures.build

  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = @category.works.new(work_params)

    respond_to do |format|
      if @work.save
        unless params[:pictures].blank?
          params[:pictures]['avatar'].each do |a|
            @picture = @work.pictures.create!(:avatar => a)
          end
        end
        format.html { redirect_to [:admin, @category, @work], notice: 'Work was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        unless params[:pictures].blank?
          params[:pictures]['avatar'].each do |a|
            @picture = @work.pictures.create!(:avatar => a)
          end
        end
        format.html { redirect_to [:admin, @category, @work], notice: 'Work was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to admin_category_works_url, notice: 'Work was successfully destroyed.' }
    end
  end

  private
    def set_category
      @category = Category.find(params[:category_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:category_id, :title, :worked_at, :content, pictures_attributes: [:id, :work_id, :avatar])
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/admin/works/_form.html.erb
<%= form_for([:admin, @category, work], :html => { :multipart => true}) do |f| %>
  <% if work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.number_field :category_id %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :worked_at %>
    <%= f.text_area :worked_at %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <%= f.fields_for :pictures do |p| %>
    <div class="field">
      <%= p.label :avatar %><br>
      <%= p.file_field :avatar, :multiple => true, name: "pictures[avatar][]" %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', [:admin, @category, @work] %> |
<%= link_to 'Back', admin_category_works_path %>

app/views/admin/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @category.title %>의 Work 리스트</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th>Worked at</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.category_id %></td>
        <td><%= work.title %></td>
        <td><%= work.worked_at %></td>
        <td><%= work.content %></td>
        <td><%= link_to '수정하기', edit_admin_category_work_path(@category, work) %></td>
        <td><%= link_to '삭제하기', [:admin, @category, work], method: :delete, data: { confirm: '정말 삭제하겠습니까?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '새 Work 생성', new_admin_category_work_path %>

app/views/admin/works/new.html.erb
<h1>New Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', admin_category_works_path %>

app/views/admin/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @work.category_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @work.title %>
</p>

<p>
  <strong>Worked at:</strong>
  <%= @work.worked_at %>
</p>

<p>
  <strong>Content:</strong>
  <%= @work.content %>
</p>

<p>
  <strong>Pictures:</strong>
  <% @work.pictures.each do |p| %>
    <%= image_tag p.avatar_url, style: "max-width: 200px;" %>
  <% end %>
</p>

<%= link_to 'Edit', edit_admin_category_work_path(@category, @work) %> |
<%= link_to 'Back', admin_category_works_path %>